### ISSUE TITLE
Tests don't work on unix-style snapshot installations

### ISSUE THREAD

**Issue by jackfirth** [racket/planet#2]
Specifically, when the [command-line integration tests](https://github.com/racket/planet/blob/master/planet-test/tests/planet/cmdline-tool.rkt#L20) try to figure out where "raco" is located:

```racket
(define raco-bin-path
  (simplify-path (build-path (collection-path "racket") 'up 'up  
                             (if (eq? (system-type) 'windows)
                                 "raco.exe"
                                 (build-path "bin" "raco")))))
```

...this implicitly assumes an in-place installation. In an in-place installation, `(build-path (collection-path "racket") 'up 'up)` returns the Racket installation directory containing `bin`, `share`, etc. directories inside it. But in an Unix-style installation of a snapshot version, the directories are laid out like this (assuming `usr` prefix):

- `/usr/bin` - contains `racket`, `raco`, etc.
- `/usr/share/racket-{version}/collects` - contains collections, including the `racket` collection.

So the test would have to go up three directories instead of two to find `./bin/raco` correctly.

I think this test would be more reliable if it instead found the Racket executable and called `raco` as a library module, e.g. `racket -l raco planet whatever...`. That can be done pretty easily using the `compiler/find-exe` library, see [here](https://github.com/jackfirth/doc-coverage/blob/master/doc-coverage/private/raco.rkt#L107) for an example.

**Comment by rfindler** [comment]
I feel better about continuing to use `raco`, but have pushed a change that makes which seems to be a smaller assumption (namely that `racket` and `raco` are in the same directory). Does that work?
